name: fetch_api_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  d_method: ^0.2.6
  dio: ^5.8.0+1
  extended_image: ^10.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
